import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PREDICTION_CSV = ROOT / "target" / "prediction_major_digit_clean_all.csv"
ADMISSION_CSV = ROOT / "target" / "admission_major_digit_clean_all.csv"
OUT_SQL = ROOT / "target" / "clean_major_digits.sql"


NUMBER_RE = re.compile(r"[0-9０-９]+(?:\.[0-9０-９]+)*")
SCHOOL_SCORE_RE = re.compile(r"（[^（）]*(?:学制|5\+3|5＋3|本博|本硕)[^（）]*）")
SCHOOL_SCORE_ASCII_RE = re.compile(r"\([^()]*?(?:学制|5\+3|5＋3|本博|本硕)[^()]*?\)")
SEPARATOR_RE = re.compile(r"[、/；;\n]+")


def q(value):
    return "'" + str(value).replace("'", "''") + "'"


def clean_piece(text):
    if not text:
        return ""
    value = str(text)
    value = SCHOOL_SCORE_RE.sub("", value)
    value = SCHOOL_SCORE_ASCII_RE.sub("", value)
    value = re.sub(r"·[0-9０-９]+·", "", value)
    value = NUMBER_RE.sub("", value)
    value = value.replace(".", "")
    value = value.replace("＋", "").replace("+", "")
    value = value.replace("：", "").replace(":", "")
    value = value.replace("·", "")
    value = re.sub(r"\s+", "", value)
    value = re.sub(r"[（(]\s*[）)]", "", value)
    value = value.strip(" 、，,；;。./")
    if not re.search(r"[\u4e00-\u9fffA-Za-z]", value):
        return ""
    return value


def clean_major_text(text):
    if text is None:
        return ""
    raw = str(text).strip()
    if not raw:
        return ""
    parts = []
    seen = set()
    for piece in SEPARATOR_RE.split(raw):
        cleaned = clean_piece(piece)
        if not cleaned or cleaned in seen:
            continue
        seen.add(cleaned)
        parts.append(cleaned)
    return "、".join(parts)


def generate_prediction_updates(lines):
    changed = 0
    with PREDICTION_CSV.open("r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            row_id = int(row["id"])
            old_direction = row.get("major_direction") or ""
            old_category = row.get("major_category") or ""
            new_direction = clean_major_text(old_direction)
            new_category = clean_major_text(old_category)
            sets = []
            if new_direction != old_direction:
                sets.append(f"major_direction={q(new_direction)}")
            if new_category != old_category:
                sets.append(f"major_category={q(new_category)}")
            if sets:
                changed += 1
                lines.append(f"UPDATE prediction_line SET {', '.join(sets)} WHERE id={row_id};")
    return changed


def generate_admission_updates(lines):
    changed = 0
    with ADMISSION_CSV.open("r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            row_id = int(row["id"])
            old_majors = row.get("majors") or ""
            new_majors = clean_major_text(old_majors)
            if new_majors != old_majors:
                changed += 1
                lines.append(f"UPDATE admission_major_group SET majors={q(new_majors)} WHERE id={row_id};")
    return changed


def main():
    lines = [
        "-- Remove OCR digits from major names.",
        "-- Generated by tools/clean_major_digits.py",
    ]
    prediction_changed = generate_prediction_updates(lines)
    admission_changed = generate_admission_updates(lines)
    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"prediction_changed={prediction_changed}")
    print(f"admission_changed={admission_changed}")
    print(OUT_SQL)


if __name__ == "__main__":
    main()
